import type { Product } from "./types";

/** Productos de ejemplo — reemplaza con tu Excel o importa a Supabase */
export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Base Líquida Matte",
    description: "Cobertura media-alta, acabado mate. Tonos disponibles.",
    price: 85000,
    category: "Rostro",
    sku: "MC-BASE-001",
    image_url: null,
    active: true,
  },
  {
    id: "2",
    name: "Corrector Creamy",
    description: "Alta cobertura para ojeras e imperfecciones.",
    price: 45000,
    category: "Rostro",
    sku: "MC-CORR-002",
    image_url: null,
    active: true,
  },
  {
    id: "3",
    name: "Paleta Sombras Nude",
    description: "12 tonos neutros y shimmer para looks diarios.",
    price: 120000,
    category: "Ojos",
    sku: "MC-SOMB-003",
    image_url: null,
    active: true,
  },
  {
    id: "4",
    name: "Máscara de Pestañas Volumen",
    description: "Volumen extremo sin grumos.",
    price: 55000,
    category: "Ojos",
    sku: "MC-MASC-004",
    image_url: null,
    active: true,
  },
  {
    id: "5",
    name: "Labial Líquido Mate",
    description: "Larga duración, no transfiere.",
    price: 38000,
    category: "Labios",
    sku: "MC-LAB-005",
    image_url: null,
    active: true,
  },
  {
    id: "6",
    name: "Brillo Labial Hidratante",
    description: "Brillo suave con vitamina E.",
    price: 32000,
    category: "Labios",
    sku: "MC-BRIL-006",
    image_url: null,
    active: true,
  },
  {
    id: "7",
    name: "Rubor en Polvo",
    description: "Color natural, fácil difuminado.",
    price: 48000,
    category: "Rostro",
    sku: "MC-RUB-007",
    image_url: null,
    active: true,
  },
  {
    id: "8",
    name: "Kit Brochas Esenciales",
    description: "Set de 5 brochas profesionales.",
    price: 95000,
    category: "Accesorios",
    sku: "MC-BRO-008",
    image_url: null,
    active: true,
  },
];

export const BRAND = {
  name: process.env.NEXT_PUBLIC_BRAND_NAME ?? "Mesana Care",
  tagline: "Belleza que cuida tu piel",
  phone: process.env.NEXT_PUBLIC_BRAND_PHONE ?? "+57 300 000 0000",
  email: process.env.NEXT_PUBLIC_BRAND_EMAIL ?? "contacto@mesanacare.com",
  instagram: "@mesanacare",
};
